trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

parameters:
  - name: browser
    displayName: 'Browser to run tests on'
    type: string
    default: 'chromium'
    values:
      - chromium
      - firefox
      - webkit

  - name: tags
    displayName: 'Test tags to run'
    type: string
    default: 'UI'
    values:
      - UI
      - Smoke
      - Regression
      - API
      - Performance
      - P1
      - P2

  - name: trace
    displayName: 'Recording a trace'
    type: string
    default: 'RETAIN_ON_FAILURE'
    values:
      - ON
      - OFF
      - RETAIN_ON_FAILURE

jobs:
  - job: RunTests
    displayName: 'Run Playwright Tests'
    strategy:
      matrix:
        Shard0:
          shardIndex: 0
          shardTotal: 4
        Shard1:
          shardIndex: 1
          shardTotal: 4
        Shard2:
          shardIndex: 2
          shardTotal: 4
        Shard3:
          shardIndex: 3
          shardTotal: 4
    container: mcr.microsoft.com/playwright/java:v1.51.0-noble
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: Maven@4
        displayName: 'Run Maven Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          options: >
            -DshardIndex=$(shardIndex)
            -DshardTotal=$(shardTotal)
            -Dgroups=$(tags)
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
        env:
          TEST_BROWSER: ${{ parameters.browser }}
          TEST_HEADLESS: "true"
          TEST_CI: "true"
          TEST_TAGS: ${{ parameters.tags }}
          TEST_TRACE: ${{ parameters.trace }}

      - task: PublishAllureReport@1
        displayName: 'Publish Allure Report'
        inputs:
          allureVersion: '2.27.0'
          testResultsDir: 'target/allure-results'
          reportName: 'Report from shard - $(shardIndex)'
