name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options: [chromium, firefox, webkit]
      tags:
        description: 'Test tags to run'
        required: true
        default: 'UI'
        type: choice
        options: [UI, Smoke, Regression, API, Performance, P1, P2]
      trace:
        description: 'Recording a trace'
        required: true
        default: 'RETAIN_ON_FAILURE'
        type: choice
        options: [ ON, OFF, RETAIN_ON_FAILURE ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.51.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '22'
#      - name: Build & Install
#        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run: mvn test -Dgroups="${TEST_TAGS}"
        env:
          TEST_BROWSER: ${{ github.event.inputs.browser }}
          TEST_HEADLESS: "true"
          TEST_CI: "true"
          TEST_TAGS: ${{ github.event.inputs.tags }}
          TEST_TRACE: ${{ github.event.inputs.trace }}

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

#      - name: Generate Allure Report
#        run: mvn allure:report
#        if: always()
#      - name: Upload Allure Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: target/allure-results/
#          retention-days: 30
#      - name: Upload Allure Report
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-report
#          path: target/site/allure-maven-plugin/
#          retention-days: 30
