name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options: [chromium, firefox, webkit]
      tags:
        description: 'Test tags to run'
        required: true
        default: 'UI'
        type: choice
        options: [UI, Smoke, Regression, API, Performance, P1, P2]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.51.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run: mvn test -Dgroups="${TEST_TAGS}"
        env:
          TEST_BROWSER: ${{ github.event.inputs.browser }}
          TEST_HEADLESS: "true"
          TEST_TAGS: ${{ github.event.inputs.tags }}
      - name: Generate Allure Report
        run: mvn allure:report
        if: always()
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 30
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
          retention-days: 30
