name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options: [chromium, firefox, webkit]
      tags:
        description: 'Test tags to run'
        required: true
        default: 'UI'
        type: choice
        options: [UI, Smoke, Regression, API, Performance, P1, P2]
      trace:
        description: 'Recording a trace'
        required: true
        default: 'RETAIN_ON_FAILURE'
        type: choice
        options: [ ON, OFF, RETAIN_ON_FAILURE ]
jobs:
  run-playwright-tests:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.51.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        id: run_tests
        continue-on-error: true
        run: mvn test -Dgroups="${TEST_TAGS}"
        env:
          TEST_BROWSER: ${{ github.event.inputs.browser }}
          TEST_HEADLESS: "true"
          TEST_CI: "true"
          TEST_TAGS: ${{ github.event.inputs.tags }}
          TEST_TRACE: ${{ github.event.inputs.trace }}

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 7

      - name: Check overall test run result
        if: steps.run_tests.outcome == 'failure'
        run: exit 1

  publish-allure-report:
    name: 'Publish Allure Report'
    needs: run-playwright-tests
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_report: allure-report
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Post the link to the report
        if: always()
        uses: guibranco/github-status-action-v2@lates
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}